### PR TITLE
Add verifier protocol

### LINKED ISSUE #24: Create base class for models
Create a base class(kind of like an abstract class) that defines methods for getting the top-k predictions. 

Probably helpful for #18.

### PR DESCRIPTION
**Pull request by r2dev2**
Adds the Verifier protocol which will be implemented by the model for getting predictions.

Fixes #24

### CODE REVIEW

**Comment by lithomas1** [comment]
@r2dev2 Can you add the dataset loading to fastapi? I don't know how to do it

**Comment by r2dev2** [comment]
> 
> 
> @r2dev2 Can you add the dataset loading to fastapi? I don't know how to do it

My bad, I meant add the model. Currently, it's hooked up to a dummy model, you need to implement the Verifier interface for the model and then replace BaseModel with the model

**Comment by r2dev2** [comment]
@lithomas1 can you review and merge. Also can you finish up the presentation. I'm figuring out how to get the demo forwarded right now since localtunnel doesn't work anymore for me.

**Review by lithomas1 — APPROVED** [review]
LGTM! Thanks @r2dev2

**Pull request merged**
